//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class area
    {
        public area()
        {
            this.area_table = new HashSet<area_table>();
        }
    
        public int AreaID { get; set; }
        public string AreaCode { get; set; }
        public int Status { get; set; }
        public Nullable<int> SystemKey { get; set; }
    
        public virtual ICollection<area_table> area_table { get; set; }
    }
}
