//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethoadontra
    {
        public int mahdt { get; set; }
        public int mamh { get; set; }
        public Nullable<int> soluongtra { get; set; }
        public Nullable<int> tinhtrang { get; set; }
    
        public virtual product product { get; set; }
        public virtual hoadontra hoadontra { get; set; }
    }
}
