//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class chitiethdn
    {
        public int MAHDN { get; set; }
        public int MAMH { get; set; }
        public int SOLUONGNHAP { get; set; }
        public decimal GIANHAP { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
    
        public virtual hoadonnhap hoadonnhap { get; set; }
        public virtual product product { get; set; }
    }
}
