//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mycoffeeEntities : DbContext
    {
        public mycoffeeEntities(string connectString)
            : base("name=mycoffeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<advancemoney> advancemoneys { get; set; }
        public DbSet<appointment> appointments { get; set; }
        public DbSet<area> areas { get; set; }
        public DbSet<area_table> area_table { get; set; }
        public DbSet<bophan> bophans { get; set; }
        public DbSet<chitiethdn> chitiethdns { get; set; }
        public DbSet<chitiethoadontra> chitiethoadontras { get; set; }
        public DbSet<company> companies { get; set; }
        public DbSet<config> configs { get; set; }
        public DbSet<congnokhachhang> congnokhachhangs { get; set; }
        public DbSet<congnoncc> congnonccs { get; set; }
        public DbSet<determine> determines { get; set; }
        public DbSet<donvitinh> donvitinhs { get; set; }
        public DbSet<employee> employees { get; set; }
        public DbSet<employeeright> employeerights { get; set; }
        public DbSet<employeestate> employeestates { get; set; }
        public DbSet<hoadonnhap> hoadonnhaps { get; set; }
        public DbSet<hoadontra> hoadontras { get; set; }
        public DbSet<icon> icons { get; set; }
        public DbSet<khachhang> khachhangs { get; set; }
        public DbSet<kho> khoes { get; set; }
        public DbSet<khuvuc> khuvucs { get; set; }
        public DbSet<listorder> listorders { get; set; }
        public DbSet<log> logs { get; set; }
        public DbSet<madein> madeins { get; set; }
        public DbSet<maillog> maillogs { get; set; }
        public DbSet<mailreceiver> mailreceivers { get; set; }
        public DbSet<managermenu> managermenus { get; set; }
        public DbSet<managerright> managerrights { get; set; }
        public DbSet<menu> menus { get; set; }
        public DbSet<money_trading> money_trading { get; set; }
        public DbSet<order_detail> order_detail { get; set; }
        public DbSet<pay_sheet> pay_sheet { get; set; }
        public DbSet<phieuchi> phieuchis { get; set; }
        public DbSet<phieuthu> phieuthus { get; set; }
        public DbSet<planwork> planworks { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<promote> promotes { get; set; }
        public DbSet<promote_detail> promote_detail { get; set; }
        public DbSet<smartlink> smartlinks { get; set; }
        public DbSet<thongtinct> thongtincts { get; set; }
        public DbSet<thue> thues { get; set; }
        public DbSet<tonkho> tonkhoes { get; set; }
    }
}
