//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class donvitinh
    {
        public donvitinh()
        {
            this.products = new HashSet<product>();
        }
    
        public int MADVT { get; set; }
        public string DONVITINH1 { get; set; }
        public int ImageIndex { get; set; }
    
        public virtual icon icon { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
