//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public employee()
        {
            this.advancemoneys = new HashSet<advancemoney>();
            this.employeestates = new HashSet<employeestate>();
            this.hoadonnhaps = new HashSet<hoadonnhap>();
            this.listorders = new HashSet<listorder>();
            this.money_trading = new HashSet<money_trading>();
            this.pay_sheet = new HashSet<pay_sheet>();
            this.phieuchis = new HashSet<phieuchi>();
            this.phieuthus = new HashSet<phieuthu>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeRight { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> EmployeeDate { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public decimal Salary { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string Notes { get; set; }
        public int Worktime { get; set; }
        public string Department { get; set; }
        public int Locked { get; set; }
        public int ChangeEmployeeCode { get; set; }
    
        public virtual ICollection<advancemoney> advancemoneys { get; set; }
        public virtual planwork planwork { get; set; }
        public virtual ICollection<employeestate> employeestates { get; set; }
        public virtual ICollection<hoadonnhap> hoadonnhaps { get; set; }
        public virtual ICollection<listorder> listorders { get; set; }
        public virtual ICollection<money_trading> money_trading { get; set; }
        public virtual ICollection<pay_sheet> pay_sheet { get; set; }
        public virtual ICollection<phieuchi> phieuchis { get; set; }
        public virtual ICollection<phieuthu> phieuthus { get; set; }
    }
}
