//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadonnhap
    {
        public hoadonnhap()
        {
            this.chitiethdns = new HashSet<chitiethdn>();
        }
    
        public int MAHDN { get; set; }
        public string HDNCode { get; set; }
        public int MANCC { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<decimal> TIENPHAITRA { get; set; }
        public Nullable<decimal> TIENDATRA { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> TINHTRANG { get; set; }
    
        public virtual ICollection<chitiethdn> chitiethdns { get; set; }
        public virtual employee employee { get; set; }
        public virtual madein madein { get; set; }
    }
}
