//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class hoadontra
    {
        public hoadontra()
        {
            this.chitiethoadontras = new HashSet<chitiethoadontra>();
        }
    
        public int ID { get; set; }
        public string mahdt { get; set; }
        public int mancc { get; set; }
        public int mahdn { get; set; }
        public Nullable<System.DateTime> ngaytra { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> tinhtrang { get; set; }
    
        public virtual ICollection<chitiethoadontra> chitiethoadontras { get; set; }
        public virtual madein madein { get; set; }
    }
}
