//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class icon
    {
        public icon()
        {
            this.donvitinhs = new HashSet<donvitinh>();
            this.menus = new HashSet<menu>();
            this.products = new HashSet<product>();
        }
    
        public int idIcon { get; set; }
        public byte[] IconName { get; set; }
        public Nullable<int> IconSkin { get; set; }
    
        public virtual ICollection<donvitinh> donvitinhs { get; set; }
        public virtual ICollection<menu> menus { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
