//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        public int MAKH { get; set; }
        public string KHCode { get; set; }
        public string TENKH { get; set; }
        public string Email { get; set; }
        public int TINHTRANG { get; set; }
        public decimal TotalMoney { get; set; }
        public int SmarkLink { get; set; }
        public Nullable<int> MAKV { get; set; }
        public string SOTAIKHOAN { get; set; }
        public string NGANHANG { get; set; }
        public string MASOTHUE { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public string FAX { get; set; }
        public string WEBSITE { get; set; }
        public string YAHOO { get; set; }
        public string SKYPE { get; set; }
    
        public virtual khuvuc khuvuc { get; set; }
        public virtual smartlink smartlink { get; set; }
    }
}
