//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class listorder
    {
        public listorder()
        {
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int OrderID { get; set; }
        public string Ordercode { get; set; }
        public int TableID { get; set; }
        public int EmployeeID { get; set; }
        public decimal Total_Money { get; set; }
        public decimal MoneyPayed { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Notes { get; set; }
        public int EmployeeTransfer { get; set; }
        public int Status { get; set; }
        public string KhachHang { get; set; }
        public Nullable<decimal> PercentMoney { get; set; }
    
        public virtual area_table area_table { get; set; }
        public virtual employee employee { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
    }
}
