//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int logid { get; set; }
        public string employeename { get; set; }
        public System.DateTime actiondate { get; set; }
        public string actions { get; set; }
    }
}
