//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class madein
    {
        public madein()
        {
            this.hoadonnhaps = new HashSet<hoadonnhap>();
            this.hoadontras = new HashSet<hoadontra>();
            this.products = new HashSet<product>();
        }
    
        public int MadeInID { get; set; }
        public string MadeInName { get; set; }
        public string ShortName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> HomePhone { get; set; }
        public Nullable<int> Telephone { get; set; }
        public Nullable<int> Fax { get; set; }
        public string Website { get; set; }
        public string Notes { get; set; }
        public string MSDKKD { get; set; }
        public string TDKKD { get; set; }
        public string MSTHUE { get; set; }
        public string DCDKKD { get; set; }
        public string SOTK { get; set; }
        public Nullable<int> KhuVuc { get; set; }
        public int Status { get; set; }
        public Nullable<int> SystemKey { get; set; }
    
        public virtual ICollection<hoadonnhap> hoadonnhaps { get; set; }
        public virtual ICollection<hoadontra> hoadontras { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
