//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class managerright
    {
        public int ID { get; set; }
        public int MenuID { get; set; }
        public sbyte m_Config { get; set; }
        public sbyte m_Employee { get; set; }
        public sbyte m_Customer { get; set; }
        public sbyte m_Product { get; set; }
        public sbyte m_Stock { get; set; }
        public sbyte m_Plankwork { get; set; }
        public sbyte m_Planday { get; set; }
        public sbyte m_Table { get; set; }
        public sbyte m_Company { get; set; }
        public sbyte m_Email { get; set; }
        public sbyte m_Empstatus { get; set; }
        public sbyte m_Advance { get; set; }
        public sbyte m_Paysheet { get; set; }
        public sbyte m_ThuChi { get; set; }
        public sbyte m_View { get; set; }
        public sbyte m_Full { get; set; }
    }
}
