//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class phieuthu
    {
        public int MaPT { get; set; }
        public string PTCode { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgayThu { get; set; }
        public Nullable<decimal> SoTienTra_PT { get; set; }
        public string Reason { get; set; }
        public string DoiTuongNop { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public string DinhKem { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
