//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class planwork
    {
        public planwork()
        {
            this.employees = new HashSet<employee>();
        }
    
        public int PlanWorkID { get; set; }
        public string PlanWorkName { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string Notes { get; set; }
        public int Status { get; set; }
        public Nullable<int> SystemKey { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
    }
}
