//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee
{
    using System;
    using System.Collections.Generic;
    
    public partial class thongtinct
    {
        public string mact { get; set; }
        public string tenct { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public string fax { get; set; }
        public byte[] logo { get; set; }
        public string masothue { get; set; }
        public string website { get; set; }
    }
}
